const std = @import("std");
const cli = @import("cli.zig");

/// Shell completion script generator
/// Generates autocompletion scripts for various shells (bash, zsh, fish)
pub const ShellCompletion = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) ShellCompletion {
        return .{ .allocator = allocator };
    }

    /// Generate Bash completion script
    pub fn generateBash(self: *ShellCompletion) ![]const u8 {
        _ = self;
        return
            \\# Den Shell - Bash completion script
            \\# Generated by 'den completion bash'
            \\#
            \\# Installation:
            \\#   den completion bash > ~/.local/share/bash-completion/completions/den
            \\#   or add to your .bashrc:
            \\#   eval "$(den completion bash)"
            \\
            \\_den_completions() {
            \\    local cur prev words cword
            \\    _init_completion || return
            \\
            \\    # Subcommands for 'den' itself
            \\    local subcommands="shell exec complete dev-setup setup set-shell uninstall version help"
            \\
            \\    # If we're completing the first argument (subcommand)
            \\    if [ "$cword" -eq 1 ]; then
            \\        COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
            \\        return 0
            \\    fi
            \\
            \\    # If first arg is 'completion', offer shell types
            \\    if [ "${words[1]}" = "completion" ] && [ "$cword" -eq 2 ]; then
            \\        COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            \\        return 0
            \\    fi
            \\
            \\    # For 'exec' or general command completion, use den's completion engine
            \\    if [ "${words[1]}" = "exec" ] || [ "${words[1]}" = "complete" ]; then
            \\        # Get the current line and delegate to 'den complete'
            \\        local line="${COMP_LINE:4}"  # Remove 'den ' prefix
            \\
            \\        # Call den complete and parse JSON output
            \\        local completions
            \\        completions=$(den complete "$cur" 2>/dev/null)
            \\
            \\        if [ -n "$completions" ]; then
            \\            # Parse JSON array and extract completions
            \\            COMPREPLY=( $(echo "$completions" | sed 's/[][]//g' | tr ',' '\n' | sed 's/"//g' | grep "^$cur") )
            \\        fi
            \\        return 0
            \\    fi
            \\
            \\    # Default: complete files
            \\    COMPREPLY=( $(compgen -f -- "$cur") )
            \\}
            \\
            \\# Register the completion function
            \\complete -F _den_completions den
            \\
        ;
    }

    /// Generate Zsh completion script
    pub fn generateZsh(self: *ShellCompletion) ![]const u8 {
        _ = self;
        return
            \\#compdef den
            \\# Den Shell - Zsh completion script
            \\# Generated by 'den completion zsh'
            \\#
            \\# Installation:
            \\#   den completion zsh > ~/.zsh/completions/_den
            \\#   or add to your .zshrc:
            \\#   eval "$(den completion zsh)"
            \\#
            \\# Make sure fpath includes your completion directory:
            \\#   fpath=(~/.zsh/completions $fpath)
            \\#   autoload -Uz compinit && compinit
            \\
            \\_den() {
            \\    local -a subcommands
            \\    subcommands=(
            \\        'shell:Start interactive shell'
            \\        'exec:Execute single command'
            \\        'complete:Get completions (JSON output)'
            \\        'completion:Generate shell completion script'
            \\        'dev-setup:Create development shim'
            \\        'setup:Install wrapper script'
            \\        'set-shell:Set Den as default shell'
            \\        'uninstall:Remove wrapper'
            \\        'version:Show version'
            \\        'help:Show help message'
            \\    )
            \\
            \\    local -a completion_shells
            \\    completion_shells=(
            \\        'bash:Generate Bash completion script'
            \\        'zsh:Generate Zsh completion script'
            \\        'fish:Generate Fish completion script'
            \\    )
            \\
            \\    _arguments -C \
            \\        '1: :->subcommand' \
            \\        '*:: :->args'
            \\
            \\    case $state in
            \\        subcommand)
            \\            _describe 'den subcommands' subcommands
            \\            ;;
            \\        args)
            \\            case $words[1] in
            \\                completion)
            \\                    _describe 'shell type' completion_shells
            \\                    ;;
            \\                exec|complete)
            \\                    # Use den's completion for dynamic suggestions
            \\                    local completions
            \\                    completions=(${(f)"$(den complete "$words[-1]" 2>/dev/null | sed 's/[][]//g' | tr ',' '\n' | sed 's/"//g')"})
            \\                    _describe 'completions' completions
            \\                    ;;
            \\                *)
            \\                    _files
            \\                    ;;
            \\            esac
            \\            ;;
            \\    esac
            \\}
            \\
            \\_den "$@"
            \\
        ;
    }

    /// Generate Fish completion script
    pub fn generateFish(self: *ShellCompletion) ![]const u8 {
        _ = self;
        return
            \\# Den Shell - Fish completion script
            \\# Generated by 'den completion fish'
            \\#
            \\# Installation:
            \\#   den completion fish > ~/.config/fish/completions/den.fish
            \\#   or add to your config.fish:
            \\#   den completion fish | source
            \\
            \\# Disable file completions by default for den
            \\complete -c den -f
            \\
            \\# Subcommands
            \\complete -c den -n "__fish_use_subcommand" -a "shell" -d "Start interactive shell"
            \\complete -c den -n "__fish_use_subcommand" -a "exec" -d "Execute single command"
            \\complete -c den -n "__fish_use_subcommand" -a "complete" -d "Get completions (JSON output)"
            \\complete -c den -n "__fish_use_subcommand" -a "completion" -d "Generate shell completion script"
            \\complete -c den -n "__fish_use_subcommand" -a "dev-setup" -d "Create development shim"
            \\complete -c den -n "__fish_use_subcommand" -a "setup" -d "Install wrapper script"
            \\complete -c den -n "__fish_use_subcommand" -a "set-shell" -d "Set Den as default shell"
            \\complete -c den -n "__fish_use_subcommand" -a "uninstall" -d "Remove wrapper"
            \\complete -c den -n "__fish_use_subcommand" -a "version" -d "Show version"
            \\complete -c den -n "__fish_use_subcommand" -a "help" -d "Show help message"
            \\
            \\# Options
            \\complete -c den -s h -l help -d "Show help message"
            \\complete -c den -s v -l version -d "Show version"
            \\
            \\# Completion subcommand arguments
            \\complete -c den -n "__fish_seen_subcommand_from completion" -a "bash" -d "Generate Bash completion"
            \\complete -c den -n "__fish_seen_subcommand_from completion" -a "zsh" -d "Generate Zsh completion"
            \\complete -c den -n "__fish_seen_subcommand_from completion" -a "fish" -d "Generate Fish completion"
            \\
            \\# Dynamic completions for exec and complete subcommands
            \\# Note: Fish has limited support for dynamic completions from JSON
            \\# For now, enable file completion for these subcommands
            \\complete -c den -n "__fish_seen_subcommand_from exec" -F
            \\complete -c den -n "__fish_seen_subcommand_from complete" -F
            \\
        ;
    }

    /// Generate completion script for specified shell
    pub fn generate(self: *ShellCompletion, shell_type: []const u8) ![]const u8 {
        if (std.mem.eql(u8, shell_type, "bash")) {
            return try self.generateBash();
        } else if (std.mem.eql(u8, shell_type, "zsh")) {
            return try self.generateZsh();
        } else if (std.mem.eql(u8, shell_type, "fish")) {
            return try self.generateFish();
        } else {
            return error.UnsupportedShell;
        }
    }
};

test "shell completion init" {
    const allocator = std.testing.allocator;
    const comp = ShellCompletion.init(allocator);
    _ = comp;
}

test "generate bash completion" {
    const allocator = std.testing.allocator;
    var comp = ShellCompletion.init(allocator);
    const script = try comp.generateBash();
    try std.testing.expect(script.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, script, "bash") != null);
}

test "generate zsh completion" {
    const allocator = std.testing.allocator;
    var comp = ShellCompletion.init(allocator);
    const script = try comp.generateZsh();
    try std.testing.expect(script.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, script, "zsh") != null);
}

test "generate fish completion" {
    const allocator = std.testing.allocator;
    var comp = ShellCompletion.init(allocator);
    const script = try comp.generateFish();
    try std.testing.expect(script.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, script, "fish") != null);
}
